name: Test on macOS

on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Set up environment
        run: |
          git config --global user.email "test@github.land"
          git config --global user.name "GitHub Almighty"

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: What is brewing
        run: |
          brew --prefix

      - name: Install git-annex
        run: |
          pip install git+https://github.com/datalad/datalad-installer@enh-brew
          datalad-installer --sudo ok -E new.env git-annex -m brew
          . new.env
          echo "PATH=$PATH" >> "$GITHUB_ENV"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install datalad

      - name: WTF!?
        run: |
          datalad wtf

      - name: Basics
        run: |
          which datalad
          which git
          which git-annex
          datalad --version
          git --version
          git annex version
